name = "vendula-handbags-api"
main = "worker.js"
compatibility_date = "2026-04-26"

[[d1_databases]]
binding = "DB"
database_name = "vendula-bags-db"
database_id = "47e3b618-2d95-47a6-9a4b-16f6d9197d86"